# Generated by Django 5.2.6 on 2025-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soildata', '0002_soiltype_alter_device_user_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
