# Generated by Django 5.2.6 on 2025-11-06 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soildata', '0004_device_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereading',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
