# Generated by Django 5.2.6 on 2025-11-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soildata', '0005_devicereading_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='soildata.device'),
        ),
    ]
