# Generated by Django 4.2 on 2025-11-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilvision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='clay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='organic_carbon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='recommended_crops',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='sand',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='silt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='soil_texture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
