# Generated by Django 4.2 on 2025-11-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilvision', '0002_soildata_clay_soildata_latitude_soildata_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soildata',
            name='clay',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='organic_carbon',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='sand',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='silt',
        ),
        migrations.AddField(
            model_name='soildata',
            name='common_locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='fertilization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='irrigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='ph_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
