# Generated by Django 4.2 on 2025-11-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilvision', '0003_remove_soildata_clay_remove_soildata_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soildata',
            name='common_locations',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='fertilization',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='irrigation',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='ph_suggestion',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='recommended_crops',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='soil_texture',
        ),
        migrations.AddField(
            model_name='soildata',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='soil_images/'),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='predicted_type',
            field=models.CharField(max_length=50),
        ),
    ]
