# Generated by Django 5.2.6 on 2025-10-10 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
        migrations.RemoveField(
            model_name='soiltype',
            name='ph_range',
        ),
        migrations.RemoveField(
            model_name='soiltype',
            name='suitable_crops',
        ),
        migrations.AddField(
            model_name='soiltype',
            name='ph_max',
            field=models.DecimalField(decimal_places=2, default=7.5, help_text='Maximum suitable pH', max_digits=4),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='ph_min',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Minimum suitable pH', max_digits=4),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
