# Generated by Django 5.2.6 on 2025-10-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcore', '0002_userprofile_delete_weather_remove_soiltype_ph_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soiltype',
            name='ph_max',
        ),
        migrations.RemoveField(
            model_name='soiltype',
            name='ph_min',
        ),
        migrations.AddField(
            model_name='soiltype',
            name='ph_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='suitable_crops',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
