# Generated by Django 5.2.6 on 2025-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcore', '0005_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
