# Generated by Django 5.2.6 on 2025-10-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcore', '0006_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soiltype',
            name='ph_range',
        ),
        migrations.AddField(
            model_name='soiltype',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='ph_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='ph_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='suitable_crops',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
