# Generated by Django 5.2.6 on 2025-10-23 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcore', '0008_device_phreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('threshold_type', models.CharField(choices=[('high', 'High'), ('low', 'Low')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soilcore.device')),
            ],
        ),
    ]
