# Generated by Django 5.2.6 on 2025-10-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcore', '0009_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soilcore.device'),
        ),
    ]
