# Generated by Django 5.2.6 on 2025-10-25 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcore', '0011_userprofile_role_alter_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soilcore.device')),
            ],
        ),
    ]
